language: node_js

node_js:
  - '10'

before_script:
  - npm install

script:
  - npm run lint
  - npm run sa
  - npm run test
  - npm run build:production
  - npm run build-userscript

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: build

notifications:
  email: false
