language: node_js

node_js:
  - '10'

before_script:
  - npm install

script:
  - npm run lint
  - npm run sa
  - npm run test
  - npm run build:prod
  - npm run build-userscript

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: build
  on:
    branch: master

notifications:
  email: false
