language: node_js

node_js:
  - '9'

before_script:
  - yarn install

script:
  - yarn lint
  - yarn static-analysis
  - yarn test


cache:
  directories:
  - 'node_modules'

notifications:
  email: false
